builders:
  routemaster_conductor:
    import: "package:routemaster_conductor/builders.dart"
    builder_factories:
      - pageRoutes
    build_extensions:
      .dart:
        - .g.dart
    auto_apply: dependents
    build_to: source
    defaults:
      dev_options:
      release_options:
        framework: routemaster
        outputDir: lib/src
      options:
        framework: routemaster
        outputDir: lib/src
